# Generated by Django 6.0.7 on 2026-07-13 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Parágrafo')),
                ('highlight', models.BooleanField(default=False, verbose_name='Destaque (cor diferente)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Parágrafo — Sobre mim',
                'verbose_name_plural': 'Parágrafos — Sobre mim',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Parágrafo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Parágrafo — Contatos',
                'verbose_name_plural': 'Parágrafos — Contatos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/', verbose_name='Foto')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Legenda')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título do serviço')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Ícone')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Doula Malú', max_length=100, verbose_name='Nome do site')),
                ('hero_title', models.CharField(default='Eu sou Malú Gomes', max_length=200, verbose_name='Título principal (hero)')),
                ('hero_subtitle', models.CharField(default='Educadora Perinatal', max_length=200, verbose_name='Subtítulo (hero)')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Foto de fundo do hero')),
                ('hero_profile_image', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Foto de perfil no hero (opcional)')),
                ('hero_cta_text', models.CharField(blank=True, default='Conheça meu trabalho', max_length=100, verbose_name='Texto do botão hero')),
                ('about_name', models.CharField(default='Malú Bezerra Gomes', max_length=200, verbose_name='Nome completo')),
                ('about_phone', models.CharField(default='(84) 98880-8252', max_length=30, verbose_name='Telefone')),
                ('about_photo', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Foto do perfil')),
                ('about_whatsapp', models.CharField(default='https://wa.me/5584988802252', max_length=200, verbose_name='Link WhatsApp')),
                ('about_instagram', models.CharField(default='https://instagram.com/doulamalu', max_length=200, verbose_name='Link Instagram')),
                ('about_quote', models.TextField(default='“Para mudar o mundo é preciso mudar a forma de nascer”.', verbose_name='Citação de destaque')),
                ('about_quote_author', models.CharField(default='— Michael Odent', max_length=100, verbose_name='Autor da citação')),
                ('services_title', models.CharField(default='Serviços', max_length=100, verbose_name='Título seção Serviços')),
                ('portfolio_title', models.CharField(default='Interessou-se pelo meu trabalho?', max_length=200, verbose_name='Título CTA portfólio')),
                ('portfolio_text', models.TextField(default='Clique no botão abaixo para baixar meu portfólio.', verbose_name='Texto CTA portfólio')),
                ('portfolio_button_text', models.CharField(default='Baixar portfólio', max_length=100, verbose_name='Texto do botão')),
                ('portfolio_file', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Arquivo do portfólio (PDF)')),
                ('portfolio_bg_image', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Imagem de fundo CTA')),
                ('contact_address', models.CharField(default='Av. Ayrtoon Senna, 1823 - Nova Parnamirim, RN', max_length=300, verbose_name='Endereço')),
                ('contact_phone', models.CharField(default='(84) 98880-8252', max_length=30, verbose_name='Telefone contato')),
                ('contact_email', models.EmailField(default='malubezarragomes21@gmail.com', max_length=254, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configuração do Site',
            },
        ),
        migrations.CreateModel(
            name='ServiceParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Parágrafo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='core.service', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Parágrafo do Serviço',
                'verbose_name_plural': 'Parágrafos do Serviço',
                'ordering': ['order'],
            },
        ),
    ]
