# Generated by Django 6.0.7 on 2026-07-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='hero_image_position',
            field=models.CharField(choices=[('center top', '⬆ Topo (mostra a parte de cima)'), ('center center', '⬛ Centro (padrão)'), ('center bottom', '⬇ Base (mostra a parte de baixo)'), ('top left', '↖ Canto superior esquerdo'), ('top right', '↗ Canto superior direito')], default='center center', help_text="Se a foto estiver cortando a face, tente 'Centro' ou 'Base'.", max_length=30, verbose_name='Posição da foto de fundo'),
        ),
    ]
