# Generated by Django 4.2.30 on 2026-07-14 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_siteconfig_hero_image_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='hero_image_position',
        ),
    ]
